
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="./link.css">
        <title></title>
        <?php 
            include("./mysqlCon.php");
            if($_SESSION["id"] == null) header("Location:./"); // 로그인 상태가 아니면 강제로 메인으로 이동
            $conn = new mysqli($host, $user, $password, $dbName);
            if(!$conn){die('연결 실패 : '.mysqli_error($conn));}
        ?>
    </head>
    <body>
        <h1>Telegram bot message translation</h1>
        <a href="./">메인으로</a><br>

        <script language="javascript">
        </script>
    </body>
</html>

