
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="./link.css">
        <title>제작자</title>
    </head>
    <body>
        <h1>182.228.58.73:51952</h1>
        <a href="../">메인으로</a><br>
        <br><br><br><br><br><br>
        <div>
            <h3>telegram bot QR</h3>
            <img src="../data/telegram_bot.jpg" alt="telegram_bot" width="500"><br>
        </div>
        <div>
            <h3>웹사이트 QR</h3>
            <img src="../data/pi2_web_site.jpg" alt="182.228.58.73:51952" width="500"><br>
        </div>
    </body>
</html>
