
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="./link.css">
        <title>계획서</title>
    </head>
    <body>
        <h1>계획서</h1>
        <h5>1889043 임동주</h5>
        <a href="../">메인으로</a><br>
        <br>
        <div>
            <h3>목표</h3>
            - 1:1 또는 1:N으로 다른 언어로 대화를 해도 번역해주는 SNS번역기
        </div>
        <div>
            <h3>기능</h3>
            - telegram의 사용자와 bot이 1:1 대화방에 참여<br>
            - 사용자는 처음 접속시 ID, password 생성<br>
            - 본인의 사용 언어를 설정<br>
            - bot을 통하여 다른사람과 연결<br>
            - 상대가 어떤 언어로 말을 해도 본인이 설정한 언어로 번역이 되어 돌아옴<br>
            - 반대로 본인이 보내는 언어도 상대방에게는 똑같이 상대방 설정대로 번역되어 감<br>
            - telegram이 없어도 웹서버를 통하여 회원을 등록하고 똑같이 사용 가능<br>
            - 대화말고 방에 혼자 있을 때 번역기의 기능도 수행<br>
        </div>
        <br>
        <div>
            <h3>구현 상황</h3>
            - <br>
            - 텔레그램 번역 echo back 구현<br>
            - 텔레그램 사용자<br>
            - 웹 페이지 구축중<br>
        </div>
        <br>
        <div>
            <h3>사용할 언어</h3>
            <img src="./data/Python_logo.png" alt="python_logo" width="300"><br>
            - python <br><br><br><br><br>
            <img src="./data/html5_logo.png" alt="html5_logo" width="300"><br>
            - HTML <br><br><br><br><br>
            <img src="./data/javascript_logo2.png" alt="javascript_logo" width="200"><br>
            - javascript <br><br><br><br><br>
            <img src="./data/css3_logo.png" alt="css3_logo" width="300"><br>
            - CSS <br><br><br><br><br>
            <img src="./data/PHP_logo.png" alt="php_logo" width="250"><br>
            - PHP <br><br><br><br><br>
            <img src="./data/Sql_logo.png" alt="Sql_logo" width="300"><br>
            - SQL <br><br><br><br><br>
        </div>
        <br>
        <div>
            <h3>사용할 도구</h3>
            <img src="./data/telegram_bot_logo.png" alt="telegram_bot_logo" width="300"><br>
            - telegram bot (python) <br><br><br><br><br>
            <img src="./data/Google-Translate-Symbol.png" alt="Google-Translate-Symbol" width="300"><br>
            - google translator (python) <br><br><br><br><br>
            <img src="./data/MariaDB_Logo.png" alt="MariaDB_Logo" width="300"><br>
            - MariaDB (python & PHP & javascript) <br><br><br><br><br>
        </div>
    </body>
</html>
